### ISSUE TITLE
Display Harmony Python package version in the UI

### ISSUE THREAD

**Issue by woodthom2** [harmonydata/app#12]
**This issue needs an API issue to be fixed first**

* Dependent on: https://github.com/harmonydata/harmonyapi/issues/3

## Description

![image](https://github.com/harmonydata/app/assets/15210965/389db5cc-d083-4047-9ad8-4bbf8f740445)

We should display to the user the version of the Harmony Python package in the UI

## Rationale

As Harmony's matching algorithm improves, people might cite Harmony and say, we got these matches with Harmony version xxxx. This should be visible in the UI, so that if someone wants to reproduce someone else's Harmony matches after Harmony is updated, they can take the old package from pypi

**Comment by ronnyTodgers** [comment]
I would certainly display it on the results page and store it with saved results models, but no harm in having it on the upload page too

**Comment by ronnyTodgers** [comment]
fixed in staging https://github.com/harmonydata/app/commit/947c727ed5fd547263d663b2262735743eb56ca3
