### ISSUE TITLE
Don't show themes in catalogue if no clear link between items and catalogue theme

### ISSUE THREAD

**Issue by bmoltrecht** [harmonydata/app#13]
Don't show themes from catalogue of MH measures if no clear link between items and catalogue themes. See image

![Harmony link to catalogue_error](https://github.com/harmonydata/app/assets/53829278/e1b3f5b0-c410-49cc-bc11-475cbc5eb053)

**Comment by ronnyTodgers** [comment]
@woodthom2 this will require the topics_auto field to carry additional information relating to the strength of the relationship which has provided that topic suggestion.

**Comment by woodthom2** [comment]
@ronnyTodgers Would this be an acceptable solution? To add a new property `topics_strengths` to the Question object? I have kind of implemented it in branch: https://github.com/harmonydata/harmony/tree/add_topic_strengths

```
{
  "question_no": null,
  "question_intro": null,
  "question_text": "Feeling nervous, anxious, or on edge",
  "options": [],
  "source_page": 0,
  "instrument_id": null,
  "instrument_name": null,
  "topics_auto": [
    "alcohol use"
  ],
  "topics_strengths": {
    "alcohol use": 0.3066757541449539
  },
  "nearest_match_from_mhc_auto": {
    "question_no": null,
    "question_intro": null,
    "question_text": "Have you ever felt annoyed by criticism of your drinking?",
    "options": [],
    "source_page": 0,
    "instrument_id": null,
    "instrument_name": null,
    "topics_auto": null,
    "topics_strengths": null,
    "nearest_match_from_mhc_auto": null
  }
}
```

**Comment by ronnyTodgers** [comment]
Looks perfect to me.

**Comment by ronnyTodgers** [comment]
Fixed in staging https://github.com/harmonydata/app/commit/947c727ed5fd547263d663b2262735743eb56ca3

Currently taking the cutoff from the main threshold slider - but perhaps it should be static at ~60%?
