### ISSUE TITLE
Add YouTube video from /app page

### ISSUE THREAD

**Issue by woodthom2** [harmonydata/app#4]
Hi John,

One suggestion that I had from people testing the tool was that we could add a link to the video or a button that can bring the video up over the page? 
We have the YT video under the fold on harmonydata.ac.uk. Do you think we could have some kind of thumbnail on the app page that would bring this up?
https://www.youtube.com/watch?v=cEZppTBj1NI

![image](https://github.com/harmonydata/app/assets/15210965/91bb7453-0b6b-45fd-b760-261ff598d72e)

**Comment by ronnyTodgers** [comment]
[That's done now](https://github.com/harmonydata/app/commit/7fa577f3ff6d6c21e18e6b876b4d7c59a78ee27f)
